defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Cheng Guo
subtitle: Ph.D. student in Operations Research, University of Toronto

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Research
    link: /research
    icon: ""

#   - text: Contact Me
#     link: /contact
#     icon: ""

  - text: My Resume
    link: /resume
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/chengguo17/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/chengg04
    icon: fab fa-github-square

#   - name: facebook
#     link: https://www.facebook.com/christian.ezeani.cyb
#     icon: fab fa-facebook-square

#   - name: twitter
#     link: https://www.twitter.com/christianezeani
#     icon: fab fa-twitter


    
